name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Create simple static page
        run: |
          mkdir -p _site/svg
          
          # Create placeholder SVGs
          echo '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 600"><rect width="800" height="600" fill="none" stroke="#ccc" stroke-width="1"/><text x="400" y="300" font-family="Arial" font-size="24" text-anchor="middle" fill="#999">Environment Layer</text></svg>' > _site/svg/environment-layer.svg
          echo '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 600"><rect width="800" height="600" fill="none" stroke="#ccc" stroke-width="1"/><text x="400" y="300" font-family="Arial" font-size="24" text-anchor="middle" fill="#999">House Structure</text></svg>' > _site/svg/house-structure.svg
          
          # Create index.html without heredoc
          echo '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>The House that Code Built</title><style>body{font-family:sans-serif;max-width:1200px;margin:0 auto;padding:20px}.three-column-layout{display:flex;width:100%}.left-column{width:25%}.center-column{width:55%}.right-column{width:20%}</style></head><body><h1>The House that Code Built</h1><div class="three-column-layout"><div class="left-column"><h2>Left Column (25%)</h2><p>About this project</p></div><div class="center-column"><h2>Center Column (55%)</h2><img src="svg/environment-layer.svg" alt="Environment" style="width:100%"></div><div class="right-column"><h2>Right Column (20%)</h2><p>View the <a href="https://github.com/TortoiseWolfe/The_House_that_Code_Built">GitHub repo</a></p></div></div></body></html>' > _site/index.html
          
          # Debug output
          echo "Generated files:"
          ls -la _site/
          ls -la _site/svg/
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3