name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy SVG assets to deploy directory
        run: mkdir -p _site/svg && cp -r _svg_assets/* _site/svg/ || true

      - name: Create simple index.html
        run: echo '<html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="description" content="The House that Code Built"><meta name="author" content="TortoiseWolfe"><title>SVG Assets</title></head><body><h1>SVG Assets</h1><p>This is a simple index page for the SVG assets.</p></body></html>' > _site/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: ./_site