name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Create site directory
        run: mkdir -p _site
        
      - name: Copy SVG assets
        run: cp -r _svg_assets _site/svg
        
      - name: Create HTML files
        run: |
          # Create index.html with proper metadata
          echo '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="description" content="The House that Code Built - Interactive Learning Tool"><meta name="author" content="TortoiseWolfe"><title>The House that Code Built</title><style>body{margin:0;padding:0;font-family:Arial,sans-serif}.container{display:flex;width:100%}.left-column{width:25%;flex:0 0 25%;background:#f0f0f0;padding:15px;box-sizing:border-box}.center-column{width:55%;flex:0 0 55%;padding:15px;box-sizing:border-box}.right-column{width:20%;flex:0 0 20%;background:#f0f0f0;padding:15px;box-sizing:border-box}</style></head><body><div class="container"><div class="left-column"><h2>Presets</h2><p>Left column (25%)</p></div><div class="center-column"><h2>Visualization</h2><img src="svg/house-structure.svg" alt="House Structure" width="100%"><img src="svg/environment-layer.svg" alt="Environment Layer" width="100%"></div><div class="right-column"><h2>Layer Controls</h2><p>Right column (20%)</p></div></div></body></html>' > _site/index.html
        
      - name: Install gh-pages
        run: npm install -g gh-pages@6.1.1
        
      - name: Deploy to GitHub Pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          npx gh-pages -d _site -t true