name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-flask
          npm install -g pa11y axe-core
      
      - name: Run accessibility unit tests
        run: |
          python -m pytest tests/test_accessibility.py -v
        
      - name: Start Flask app for accessibility testing
        run: |
          python app.py &
          sleep 3  # Give Flask time to start
          
      - name: Run automated accessibility tests
        run: |
          pa11y http://localhost:5000 --standard WCAG2AA --reporter json > accessibility-report.json
          
      - name: Check for critical issues
        run: |
          errors=$(cat accessibility-report.json | grep -c '"type":"error"' || echo "0")
          if [ "$errors" -gt "0" ]; then
            echo "Found $errors accessibility errors. See accessibility-report.json for details."
            exit 1
          else
            echo "No critical accessibility issues found!"
          fi
          
      - name: Upload accessibility report
        uses: actions/upload-artifact@v3
        with:
          name: accessibility-report
          path: accessibility-report.json

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask python-dotenv
      
      - name: Build static site
        run: |
          mkdir -p gh-pages/svg
          
          # Copy SVG files from _svg_assets if they exist
          if [ -d "_svg_assets" ]; then
            cp _svg_assets/*.svg gh-pages/svg/ || true
          fi
          
          # Copy SVG files from static/svg if they exist
          if [ -d "static/svg" ]; then
            cp static/svg/*.svg gh-pages/svg/ || true
          fi
          
          # Create simple index.html for GitHub Pages
          cat > gh-pages/index.html << 'EOL'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta name="description" content="Interactive visualization of web development concepts using a house metaphor">
            <title>The House that Code Built</title>
            <style>
              body {
                font-family: 'Segoe UI', sans-serif;
                max-width: 1200px;
                margin: 0 auto;
                padding: 20px;
                background-color: #f5f5f5;
                color: #333;
                line-height: 1.5;
              }
              h1 { color: #2e7d32; text-align: center; }
              .container { display: flex; flex-direction: column; gap: 20px; }
              .svg-container {
                background-color: #fff;
                border-radius: 8px;
                padding: 20px;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                min-height: 600px;
                position: relative;
              }
              .button {
                display: inline-block;
                padding: 10px 15px;
                background-color: #2196F3;
                color: white;
                text-decoration: none;
                border-radius: 4px;
                font-weight: bold;
              }
              .github-link { margin-top: 30px; text-align: center; }
              footer { margin-top: 40px; text-align: center; }
            </style>
          </head>
          <body>
            <h1>The House that Code Built</h1>
            <main class="container">
              <section class="svg-container">
                <object data="svg/environment-layer.svg" type="image/svg+xml" style="position:absolute;top:0;left:0;width:100%;height:100%"></object>
                <object data="svg/house-structure.svg" type="image/svg+xml" style="position:absolute;top:0;left:0;width:100%;height:100%"></object>
              </section>
              <div class="github-link">
                <p>To view the interactive version with all layers:</p>
                <a href="https://github.com/TortoiseWolfe/The_House_that_Code_Built" class="button">View on GitHub</a>
              </div>
            </main>
            <footer>
              <p>This project follows WCAG 2.1 AA accessibility guidelines</p>
            </footer>
          </body>
          </html>
          EOL
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './gh-pages'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
